name: Fetch Global Weather

on:
  push:                     # Trigger on any push to the repository
  schedule:
    - cron: '0 * * * *'     # Runs every hour
  workflow_dispatch:        # Allows manual trigger

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run CLI weather fetch script
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: go run city.go
      working-directory: ./weather

    - name: Test weather web server
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        nohup go run weather.go &
        sleep 5  # Give server time to start
        curl -s "http://localhost:8080/weather?city=London" > response.html
        grep "London" response.html
      working-directory: ./weather

